---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-cluster-rolebinding
  namespace: default
subjects:
- kind: User
  name: user1
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: eks-cluster-role
  apiGroup: rbac.authorization.k8s.io
