kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-cluster-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - 'pods'
  verbs:
  - get
  - list
  - update
  - create
  - delete
